accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),


]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path("", views.main, name="main"),
]

mypageapp/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path("", views.mypage, name="mypage"),
]

proto_dc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import main.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.main),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('mypage/', include('mypageapp.urls')),
    path('search/', include('searchapp.urls')),
    path('crawling/', include('crawlingapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


searchapp/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "searchapp"

urlpatterns = [
    path("", views.uploadFile, name="uploadFile"),
]

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, UserChangeForm
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import get_user_model
from .choice import *

def hp_validator(value):
    if len(str(value)) != 10:
        raise forms.ValidationError('정확한 핸드폰 번호를 입력해주세요.')


class CsRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CsRegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False
        })
        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False

        })

    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'email', 'name', 'hp']

    def save(self, commit=True):
        user = super(CsRegisterForm, self).save(commit=False)
        user.level = '0'
        user.department = '일반'
        user.is_active = True
        user.save()

        return user

# 로그인 폼
class LoginForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', }),
        error_messages={'required': '아이디을 입력해주세요.'},
        max_length=17,
        label='아이디'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', }),
        error_messages={'required': '비밀번호를 입력해주세요.'},
        label='비밀번호'
    )

    def clean(self):
        cleaned_data = super().clean()
        user_id = cleaned_data.get('user_id')
        password = cleaned_data.get('password')

        if user_id and password:
            try:
                user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                self.add_error('user_id', '아이디가 존재하지 않습니다.')
                return

            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')

# 비밀번호찾기 폼
class RecoveryPwForm(forms.Form):
    user_id = forms.CharField(widget=forms.TextInput,)
    name = forms.CharField(widget=forms.TextInput,)
    email = forms.EmailField(widget=forms.EmailInput,)

    class Meta:
        fields = ['user_id', 'name', 'email']

    def __init__(self, *args, **kwargs):
        super(RecoveryPwForm, self).__init__(*args, **kwargs)
        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            'class': 'form-control',
            'id': 'pw_form_id',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'id': 'pw_form_name',
        })

# 아이디찾기 폼
class RecoveryIdForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput,)
    email = forms.EmailField(widget=forms.EmailInput,)

    class Meta:
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super(RecoveryIdForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'id': 'form_name',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'pw_form_email',
        })

# 비밀번호찾기 새 비밀번호 입력 폼
class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomSetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })


class CustomCsUserChangeForm(UserChangeForm):
    password = None
    hp = forms.IntegerField(label='연락처', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength':'11', 'oninput':"maxLengthCheck(this)",}),
    )
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',}),
    )
    class Meta:
        model = User()
        fields = ['hp', 'name']

accounts/views.py
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from .decorators import *
from .models import User
from django.views.generic import View,CreateView
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from .forms import CsRegisterForm, LoginForm, RecoveryPwForm, CustomSetPasswordForm
from django.urls import reverse
from .helper import send_mail, email_auth_num
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import login, logout, authenticate
from django.views.generic import FormView
from django.conf import settings
from django.core.exceptions import ValidationError
from .forms import RecoveryIdForm, CustomCsUserChangeForm
from django.views.generic import View
import json
from django.core.serializers.json import DjangoJSONEncoder


@login_message_required
def main_view(request):
    return render(request, 'main/main.html')

# 회원가입
class CsRegisterView(CreateView):
    model = User
    template_name = 'accounts/register_cs.html'
    form_class = CsRegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        return reverse('accounts:register_success')


    def form_valid(self, form):
        self.object = form.save()

        send_mail(
            '{}님의 회원가입 인증메일 입니다.'.format(self.object.user_id),
            [self.object.email],
            html=render_to_string('accounts/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            }),
        )
        return redirect(self.get_success_url())

# 이메일 인증 활성화
def activate(request, uid64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('accounts:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('accounts:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('accounts:login')

@login_message_required
def main_view(request):
    return render(request, 'main/main.html')

# 회원가입 약관동의
@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'accounts/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True

            if request.POST.get('csregister') == 'csregister':
                return redirect('../csregister/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'accounts/agreement.html')

# 회원가입 인증메일 발송 안내 창
def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'accounts/register_success.html')

# 로그인
@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = '../main/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=user_id, password=password)
        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)
            remember_session = self.request.POST.get('remember_session', False)


        return super().form_valid(form)

# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('/')

# 비밀번호찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryPwView(View):
    template_name = 'accounts/recovery_pw.html'
    recovery_pw = RecoveryPwForm

    def get(self, request):
        if request.method=='GET':
            form = self.recovery_pw(None)
            return render(request, self.template_name, { 'form_pw':form, })

# 아이디찾기 AJAX 통신
def ajax_find_pw_view(request):
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')
    target_user = User.objects.get(user_id=user_id, name=name, email=email)

    if target_user:
        auth_num = email_auth_num()
        target_user.auth = auth_num
        target_user.save()

        # send_mail(
        #     '비밀번호 찾기 인증메일입니다.',
        #     [email],
        #     html=render_to_string('accounts/recovery_email.html', {
        #         'auth_num': auth_num,
        #     }),
        # )
    return HttpResponse(json.dumps({"result": target_user.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")

# 비밀번호찾기 인증번호 확인
def auth_confirm_view(request):
    user_id = request.POST.get('user_id')
    input_auth_num = request.POST.get('input_auth_num')
    target_user = User.objects.get(user_id=user_id, auth=input_auth_num)
    target_user.auth = ""
    target_user.save()
    request.session['auth'] = target_user.user_id

    return HttpResponse(json.dumps({"result": target_user.user_id}, cls=DjangoJSONEncoder),
                        content_type="application/json")


@logout_message_required
def auth_pw_reset_view(request):
    if request.method == 'GET':
        if not request.session.get('auth', False):
            raise PermissionDenied

    if request.method == 'POST':
        session_user = request.session['auth']
        current_user = User.objects.get(user_id=session_user)
        login(request, current_user)

        reset_password_form = CustomSetPasswordForm(request.user, request.POST)

        if reset_password_form.is_valid():
            user = reset_password_form.save()
            messages.success(request, "비밀번호 변경완료! 변경된 비밀번호로 로그인하세요.")
            logout(request)
            return redirect('accounts:login')
        else:
            logout(request)
            request.session['auth'] = session_user
    else:
        reset_password_form = CustomSetPasswordForm(request.user)

    return render(request, 'accounts/password_reset.html', {'form': reset_password_form})


@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'accounts/recovery_id.html'
    form = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form = self.recovery_id(None)
        return render(request, self.template_name, { 'form':form, })


def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)

    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder),
                        content_type="application/json")


# 아이디찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'accounts/recovery_id.html'
    recovery_id = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form_id = self.recovery_id(None)
        return render(request, self.template_name, { 'form_id':form_id, })


def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)

    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder),
                        content_type="application/json")

def main(request):
    return render(request, 'main/main.html')

@login_message_required
def profile_view(request):
    if request.method == 'GET':
        return render(request, 'accounts/profile.html')


@login_message_required
def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'accounts/profile.html')
    else:
        user_change_form = CustomCsUserChangeForm(instance = request.user)

        return render(request, 'accounts/profile_update.html', {'user_change_form':user_change_form})

accounts/templates/accounts/accounts_base.html
<html>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% block header %}
    <!-- header 삽입 부분 -->
    {% endblock %}
</head>

<body style="background-color: #d6d6d6;">
    {% include 'nav.html' %}

    {% block contents %}
    <!-- body 삽입 부분 -->
    {% endblock %}

    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <script>
        alert("{{ message.message }}") <!-- message alert script -->
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</html>

accounts/templates/accounts/nav.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'main:main' %}"><img src="{% static 'img/logo1.jpg' %}" style="width:100px;height:60px; margin-left: 30px;" alt="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-left: 500px;">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
              이미지 검색하기
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#" >서비스 소개</a></li>
              <li><a class="dropdown-item" href="{%url 'searchapp:uploadFile' %}">이미지 검색하기</a></li>
              <li><a class="dropdown-item" href="#">피해구제방법</a></li>
            </ul>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#" style="color: white; margin-left: 30px;">게시판</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'mypage:mypage' %}" style="color: white; margin-left: 30px;">마이페이지</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" style="color: white; margin-left: 30px;">로그아웃</a></li>
          <li class="nav-item" style="color: white; margin-left: 30px">{{user}}님, 반갑습니다.</li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" style="color: white; margin-left: 30px;">로그인</a></li>
          {% endif %}
  
        </ul>
      </div>
    </div>
  </nav>

accounts/templates/accounts/recovery_pw.html
{% extends "accounts/accounts_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=510, user-scalable=yes">
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/loading.css' %}" type="text/css">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row justify-content-md-center">
        <div style="position: absolute; top: 45%; height: 504.18px; margin-top: -252.09px;">
            <div class="card"  style="width: 32rem; margin-left: 35%; margin-top: 1%;">
                <div class="card-body">
                    <div class="text-center">
                        <img src="{% static 'img/logo.jpg' %}" style="width:60%; margin:30px; border-radius: 20px; margin-bottom: 30px;">
                    </div>
                    <div class="row mt-5">
                        <div class="col-12">
                            {% csrf_token %}
                            <!--아이디-->
                            <div class="mb-4 md-form">
                                <label name="label_user_id" for="{{ form_pw.user_id.id_for_label }}"><i
                                    class="fas fa-user"></i>&nbsp;&nbsp;{{ form_pw.user_id.label }}</label>
                                    {{ form_pw.user_id }}
                            </div>

                            <!--이름-->
                            <div class="mb-4 md-form">
                                <label name="label_name" for="{{ form_pw.name.id_for_label }}"><i
                                    class="fas fa-user-edit"></i>&nbsp;&nbsp;{{ form_pw.name.label }}</label>
                                    {{ form_pw.name }}
                            </div>

                            <!--이메일-->
                            <div class="mb-4 md-form">
                                <label name="label_email" for="{{ form_pw.email.id_for_label }}"><i
                                        class="fas fa-envelope"></i>&nbsp;&nbsp;{{ form_pw.email.label }}</label><br>
                                    {{ form_pw.email }}
                                    <br>
                                <small class="form-text text-muted" style="margin-left:25%">
                                    등록하신 메일로 인증번호가 발송됩니다.
                                </small>
                            </div>
                            <!--비밀번호찾기 버튼-->
                            <div id="div_find_pw" style="padding-top:10px;" class="row justify-content-md-center">
                                <button id="find_pw" class="btn btn-dark btn-md" style="text-align:center; font-size: 16px; width: 130px;" name="recovery_pw"><i class="fas fa-search"></i>비밀번호찾기</button>
                            </div>

                            <div style="text-align: center; margin-top: 10px; margin-bottom: -10px;">
                                <div id="loading"></div>
                            </div>

                            <div id="result_pw"></div>

                            <br>
                            <span style="color:gray; font-size: 14px;" >아이디를 잊으셨나요?</span>
                            <a style="text-decoration:underline; color:black; font-size: 14px;" href="{% url 'accounts:recovery_id' %}">아이디찾기</a>
                            <script src="http://code.jquery.com/jquery-latest.js"></script>
                            <script type="text/javascript">
                                $(document).ready(function () {
                                    $('#find_pw').click(function () {
                                        $('#loading').replaceWith('<div id="loading_end" class="loading"></div>')
                                        var user_id = $("#pw_form_id").val();
                                        var name = $("#pw_form_name").val();
                                        var email = $("#pw_form_email").val();

                                        $.ajax({
                                            type: "POST",
                                            url: "/accounts/recovery/pw/find/",
                                            dataType: "json",
                                            data: {
                                                'user_id': user_id,
                                                'name': name,
                                                'email': email,
                                                'csrfmiddlewaretoken': '{{csrf_token}}',
                                            },
                                            success: function (response) {
                                                $('#loading_end').remove()
                                                alert('회원님의 이메일로 인증코드를 발송하였습니다.');
                                                // $('#result_pw').replaceWith('<h5><p id="result_pw">회원님의 비밀번호는 <strong>'+response.result_pw+'</strong> 입니다.</p></h5>')
                                                $('#div_find_pw').remove()
                                                $('#result_pw').replaceWith(
                                                    // '<br><form action="{% url "accounts:recovery_auth" %}" method="POST"><input type="text" name="input_auth_num" placeholder="인증번호를 입력해주세요." class="form-control" /><br><button type="submit" name="auth_confirm" class="btn btn-danger">인증확인</button></form>'
                                                    '<hr><div class="row justify-content-md-center"><form class="form-inline" style="margin-bottom:-15px; margin-top:-10px;"><div class="md-form md-outline"><label for="input_auth_num">인증번호 입력 (<span id="timeset"></span>)</label><input type="text" id="input_auth_num" class="form-control mx-sm-2" autofocus/></div></form>'+
                                                    '<button type="submit" name="auth_confirm" id="id_auth_confirm" class="btn btn-red" style="opacity: 90%; height:30%; margin-top:10px; font-size: 12px;"><i class="fas fa-check"></i>&nbsp;&nbsp;인증확인</button></div><hr>'
                                                )
                                                function countdown( elementName, minutes, seconds ) {
                                                    var elementName, endTime, hours, mins, msLeft, time;
                                                    function twoDigits( n ) {
                                                        return (n <= 9 ? "0" + n : n);
                                                    }
                                                    function updateTimer() {
                                                        msLeft = endTime - (+new Date);
                                                        if ( msLeft < 1000 ) {
                                                            alert("인증시간이 초과되었습니다.");
                                                            $("" + elementName).remove();
                                                            cert_ok = false;
                                                            certificationNum = false;
                                                            location.href = "{% url 'accounts:recovery_pw' %}"
                                                        } else {
                                                            time = new Date( msLeft );
                                                            hours = time.getUTCHours();
                                                            mins = time.getUTCMinutes();
                                                            $("" + elementName).html((hours ? hours + ':' + twoDigits( mins ) : twoDigits(mins))
                                                            + ':' + twoDigits( time.getUTCSeconds()));
                                                            setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
                                                        }
                                                    }
                                                    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
                                                    updateTimer();
                                                }
                                                countdown("#timeset", 5, 0);

                                                var user = response.result

                                                $(document).ready(function () {
                                                    $('#id_auth_confirm').click(function () {
                                                        var input_auth_num = $("#input_auth_num").val();

                                                        $.ajax({
                                                            type: "POST",
                                                            url: "/accounts/recovery/pw/auth/",
                                                            dataType: "json",
                                                            data: {
                                                                'user_id': user,
                                                                'input_auth_num': input_auth_num,
                                                                'csrfmiddlewaretoken': '{{csrf_token}}',
                                                            },
                                                            success: function (response) {
                                                                // location.href = "/accounts/profile/password/";
                                                                location.href = "{% url 'accounts:recovery_pw_reset' %}";
                                                            },
                                                            error: function () {
                                                                if ($('#input_auth_num').val()=="") {
                                                                    alert('회원님의 이메일로 전송된 인증번호를 입력해주세요.');
                                                                } else {
                                                                    alert('인증번호가 일치하지 않습니다.');
                                                                }
                                                            },
                                                        });
                                                    })
                                                })
                                            },
                                            error: function () {
                                                $('#loading_end').remove()
                                                if (user_id == "" || name == "" || email == "") {
                                                    alert('아이디, 이름, 이메일을 모두 입력해주세요.');
                                                } else {
                                                    alert('입력하신 정보가 일치하지 않거나 존재하지 않습니다.');
                                                }
                                            },
                                        });
                                    })
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register_email.html
{% include 'nav.html' %}

{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 이메일 인증 발송</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;"> 홈페이지 회원가입을 축하드립니다.<br>아래 링크를 클릭하여 로그인 해주시기 바랍니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'accounts:activate' uid64=uid token=token %}">인증하기</a></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}

accounts/templates/accounts/register_success.html
{% include 'nav.html' %}

<h1> hello world </h1>