accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('csregister/', views.CsRegisterView.as_view(), name='csregister'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),


]

crawlingapp/urls.py
from django.urls import path
from . import views

app_name = 'crawling'
urlpatterns = [
    path('', views.crawlingmain, name="main"),
    path('start/', views.crawlingstart, name="start"),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path("", views.main, name="main"),
]

mypageapp/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path("", views.mypage, name="mypage"),
]

proto_dc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import main.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.main),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('mypage/', include('mypageapp.urls')),
    path('search/', include('searchapp.urls')),
    path('crawling/', include('crawlingapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


searchapp/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "searchapp"

urlpatterns = [
    path("", views.uploadFile, name="uploadFile"),
]

main/views.py
from django.shortcuts import render, redirect


def main(request):
    return render(request, 'main/main.html')

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> 디지털 장의사 </title>
</head>
<body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

main/templates/nav.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'main:main' %}"><img src="{% static 'img/logo1.jpg' %}" style="width:100px;height:60px; margin-left: 30px;" alt="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div style="float:right;">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
                이미지 검색하기
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#" >서비스 소개</a></li>
                <li><a class="dropdown-item" href="{%url 'searchapp:uploadFile' %}">이미지 검색하기</a></li>
                <li><a class="dropdown-item" href="#">피해구제방법</a></li>
              </ul>
            </li>
  
            <li class="nav-item">
              <a class="nav-link" href="{%url 'crawling:main' %}" style="color: white; margin-left: 30px;">게시판</a>
            </li>
  
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'mypage:mypage' %}" style="color: white; margin-left: 30px;">마이페이지</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}" style="color: white; margin-left: 30px;">로그아웃</a></li>
            <li class="nav-item" style="color: white; margin-left: 30px">{{user}}님, 반갑습니다.</li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}" style="color: white; margin-left: 30px;">로그인</a></li>
            {% endif %}
    
          </ul>
        </div>
      </div>
  
      </div>
        </nav>